<a href="https://colab.research.google.com/github/emanuelmejia/course_time_series_python/blob/main/L01-Intro_TS/notebooks/L01_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import files
files.upload()

Saving cbe.dat to cbe (1).dat

{'cbe (1).dat': b'choc\tbeer\telec\n1451\t96.3\t1497\n2037\t84.4\t1463\n2477\t91.2\t1648\n2785\t81.9\t1595\n2994\t80.5\t1777\n2681\t70.4\t1824\n3098\t74.8\t1994\n2708\t75.9\t1835\n2517\t86.3\t1787\n2445\t98.7\t1699\n2087\t100.9\t1633\n1801\t113.8\t1645\n1216\t89.8\t1597\n2173\t84.4\t1577\n2286\t87.2\t1709\n3121\t85.6\t1756\n3458\t72\t1936\n3511\t69.2\t2052\n3524\t77.5\t2105\n2767\t78.1\t2016\n2744\t94.3\t1914\n2603\t97.7\t1925\n2527\t100.2\t1824\n1846\t116.4\t1765\n1066\t97.1\t1721\n2327\t93\t1752\n3066\t96\t1914\n3048\t80.5\t1857\n3806\t76.1\t2159\n4042\t69.9\t2195\n3583\t73.6\t2287\n3438\t92.6\t2276\n2957\t94.2\t2096\n2885\t93.5\t2055\n2744\t108.5\t2004\n1837\t109.4\t1924\n1447\t105.1\t1851\n2504\t92.5\t1839\n3248\t97.1\t2019\n3098\t81.4\t1937\n4318\t79.1\t2270\n3561\t72.1\t2251\n3316\t78.7\t2382\n3379\t87.1\t2364\n2717\t91.4\t2129\n2354\t109.9\t2110\n2445\t116.3\t2072\n1542\t113\t1980\n1606\t100\t1995\n2590\t84.8\t1932\n3588\t94.3\t2171\n3202\t87.1\t2162\n4704\t90.3\t2489\n4005\t72.4\t2424\n3810\t84.9\t2641\n3488\t92.7\t2630\n2781\t92.2\t2324\n2944\t114.9\t2412\n2817\t112.5\t2284\n1960\t118.3\t2186\n1937\t106\t2184\n2903\t91.2\t2144\n3357\t96.6\t2379\n3552\t96.3\t2383\n4581\t88.2\t2717\n3905\t70.2\t2774\n4581\t86.5\t3051\n4037\t88.2\t2891\n3345\t102.8\t2613\n3175\t119.1\t2600\n2808\t119.2\t2493\n2050\t125.1\t2410\n1719\t106.1\t2390\n3143\t102.1\t2463\n3756\t105.2\t2616\n4776\t101\t2734\n4540\t84.3\t2970\n4309\t87.5\t3125\n4563\t92.7\t3342\n3506\t94.4\t3207\n3665\t113\t2964\n3361\t113.9\t2919\n3094\t122.9\t2764\n2440\t132.7\t2732\n1633\t106.9\t2622\n2935\t96.6\t2698\n4159\t127.3\t2950\n4159\t98.2\t2895\n4894\t100.2\t3200\n4921\t89.4\t3408\n4577\t95.3\t3679\n4155\t104.2\t3473\n3851\t106.4\t3154\n3429\t116.2\t3107\n3370\t135.9\t3052\n2726\t134\t2918\n1674\t104.6\t2786\n3257\t107.1\t2739\n4731\t123.5\t3125\n4481\t98.8\t3033\n5443\t98.6\t3486\n5566\t90.6\t3661\n5044\t89.1\t3927\n4781\t105.2\t3851\n4014\t114\t3456\n3561\t122.1\t3390\n3801\t138\t3280\n2685\t142.2\t3166\n1805\t116.4\t3080\n3756\t112.6\t3069\n4227\t123.8\t3340\n4595\t103.6\t3310\n5702\t113.9\t3798\n4681\t98.6\t3883\n4395\t95\t4191\n4459\t116\t4213\n4191\t113.9\t3766\n3742\t127.5\t3628\n3279\t131.4\t3520\n2468\t145.9\t3322\n1742\t131.5\t3250\n3366\t131\t3287\n3633\t130.5\t3552\n3701\t118.9\t3440\n4926\t114.3\t4153\n4522\t85.7\t4265\n5275\t104.6\t4655\n4717\t105.1\t4492\n4114\t117.3\t4051\n3851\t142.5\t3967\n3493\t140\t3807\n2654\t159.8\t3639\n2168\t131.2\t3647\n3561\t125.4\t3560\n4305\t126.5\t3929\n4413\t119.4\t3858\n5307\t113.5\t4485\n5361\t98.7\t4697\n4948\t114.5\t4977\n4472\t113.8\t4675\n3846\t133.1\t4596\n3715\t143.4\t4491\n3343\t137.3\t4127\n2939\t165.2\t4144\n1615\t126.9\t4014\n3497\t124\t3994\n3915\t135.7\t4320\n4858\t130\t4400\n4962\t109.4\t5002\n4504\t117.8\t5091\n4767\t120.3\t5471\n4291\t121\t5193\n4091\t132.3\t4997\n4164\t142.9\t4737\n3915\t147.4\t4546\n3130\t175.9\t4498\n1696\t132.6\t4350\n3887\t123.7\t4206\n4749\t153.3\t4743\n4781\t134\t4582\n5089\t119.6\t5191\n5484\t116.2\t5457\n5072\t118.6\t5891\n4611\t130.7\t5618\n4117\t129.3\t5158\n3910\t144.4\t5030\n4252\t163.2\t4800\n3624\t179.4\t4654\n1678\t128.1\t4453\n3851\t138.4\t4440\n5021\t152.7\t4945\n4581\t120\t4788\n6195\t140.5\t5425\n5338\t116.2\t5706\n4909\t121.4\t6061\n4640\t127.8\t5846\n3706\t143.6\t5242\n4113\t157.6\t5408\n3879\t166.2\t5114\n3411\t182.3\t5042\n2043\t153.1\t5008\n3736\t147.6\t4657\n4490\t157.7\t5359\n3715\t137.2\t5193\n5623\t151.5\t5891\n4671\t98.7\t5980\n5591\t145.8\t6390\n5461\t151.7\t6366\n4795\t129.4\t5756\n4846\t174.1\t5640\n4843\t197\t5429\n3278\t193.9\t5398\n2411\t164.1\t5413\n4278\t142.8\t5141\n4639\t157.9\t5695\n4559\t159.2\t5554\n6404\t162.2\t6369\n4851\t123.1\t6592\n6480\t130\t7107\n6394\t150.1\t6917\n5752\t169.4\t6353\n4718\t179.7\t6205\n4659\t182.1\t5830\n3842\t194.3\t5646\n2873\t161.4\t5379\n5556\t169.4\t5489\n5389\t168.8\t5824\n6135\t158.1\t5907\n6707\t158.5\t6482\n5220\t135.3\t6795\n6249\t149.3\t7028\n5281\t143.4\t6776\n4192\t142.2\t6274\n4867\t188.4\t6362\n3752\t166.2\t5940\n3492\t199.2\t5958\n1979\t182.7\t5769\n4584\t145.2\t5887\n5139\t182.1\t6367\n5044\t158.7\t6165\n5501\t141.6\t6868\n5044\t132.6\t7201\n5035\t139.6\t7601\n5167\t147\t7581\n4650\t166.6\t7090\n5298\t157\t6841\n4373\t180.4\t6408\n3941\t210.2\t6435\n2334\t159.8\t6176\n4381\t157.8\t6138\n5665\t168.2\t6717\n4393\t158.4\t6470\n5232\t152\t7312\n5876\t142.2\t7763\n5900\t137.2\t8171\n5704\t152.6\t7788\n4718\t166.8\t7311\n4650\t165.6\t6679\n4446\t198.6\t6704\n3061\t201.5\t6724\n2155\t170.7\t6552\n4274\t164.4\t6427\n4695\t179.7\t7105\n4362\t157\t6869\n4889\t168\t7683\n5370\t139.3\t8082\n5072\t138.6\t8555\n4985\t153.4\t8386\n3978\t138.9\t7553\n4139\t172.1\t7398\n3995\t198.4\t7112\n3025\t217.8\t6886\n1949\t173.7\t7077\n4357\t153.8\t6820\n4638\t175.6\t7426\n3994\t147.1\t7143\n6174\t160.3\t8261\n5656\t135.2\t8240\n4411\t148.8\t8977\n5504\t151\t8991\n4463\t148.2\t8026\n4458\t182.2\t7911\n4528\t189.2\t7510\n2830\t183.1\t7381\n1843\t170\t7366\n5042\t158.4\t7414\n5348\t176.1\t7824\n5257\t156.2\t7524\n6699\t153.2\t8279\n5388\t117.9\t8707\n6001\t149.8\t9486\n5966\t156.6\t8973\n4845\t166.7\t8231\n4507\t156.8\t8206\n4214\t158.6\t7927\n3460\t210.8\t7999\n1833\t203.6\t7834\n4978\t175.2\t7521\n6464\t168.7\t8284\n5820\t155.9\t7999\n6447\t147.3\t8940\n6191\t137\t9381\n6628\t141.1\t10078\n5452\t167.4\t9796\n5295\t160.2\t8471\n5080\t191.9\t8572\n5564\t174.4\t8150\n3965\t208.2\t8168\n2062\t159.4\t8166\n5099\t161.1\t7903\n6162\t172.1\t8606\n5529\t158.4\t8071\n6416\t114.6\t9178\n6382\t159.6\t9873\n5624\t159.7\t10476\n5785\t159.4\t9296\n4644\t160.7\t8818\n5331\t165.5\t8697\n5143\t205\t8381\n4596\t205.2\t8293\n2180\t141.6\t7942\n5786\t148.1\t8001\n5840\t184.9\t8744\n5666\t132.5\t8397\n6360\t137.3\t9115\n6219\t135.5\t9773\n6082\t121.7\t10358\n5653\t166.1\t9849\n5726\t146.8\t9083\n5049\t162.8\t9143\n5859\t186.8\t8800\n4091\t185.5\t8741\n2167\t151.5\t8492\n6480\t158.1\t8795\n7375\t143\t9354\n6583\t151.2\t8796\n7251\t147.6\t10072\n6730\t130.7\t10174\n6428\t137.5\t11326\n5228\t146.1\t10744\n4716\t133.6\t9806\n6101\t167.9\t9740\n5753\t181.9\t9373\n4000\t202\t9244\n2691\t166.5\t9407\n5898\t151.3\t8827\n6526\t146.2\t9880\n5840\t148.3\t9364\n6650\t144.7\t10580\n5717\t123.6\t10899\n7236\t151.6\t11687\n6523\t133.9\t11280\n5729\t137.4\t10208\n6004\t181.6\t10212\n5950\t182\t9725\n4690\t190\t9721\n3687\t161.2\t9846\n7791\t155.5\t9407\n7153\t141.9\t10265\n6434\t164.6\t9970\n7850\t136.2\t10801\n6809\t126.8\t11246\n8379\t152.5\t12167\n6914\t126.6\t11578\n6919\t150.1\t10645\n7265\t186.3\t10613\n6994\t147.5\t10104\n5503\t200.4\t10348\n3782\t177.2\t10263\n7502\t127.4\t9973\n8119\t177.1\t10803\n7292\t154.4\t10409\n6886\t135.2\t11458\n7049\t126.4\t11845\n7977\t147.3\t12559\n8519\t140.6\t12070\n6680\t152.3\t11221\n7994\t151.2\t11338\n7047\t172.2\t10761\n5782\t215.3\t11012\n3771\t154.1\t10923\n7906\t159.3\t10790\n8970\t160.4\t11427\n6077\t151.9\t10788\n7919\t148.4\t11772\n7340\t139.6\t12104\n7791\t148.2\t12634\n7368\t153.5\t12772\n8255\t145.1\t11764\n7816\t183.7\t11956\n7476\t210.5\t11646\n6696\t203.3\t11750\n4484\t153.3\t11485\n8274\t144.3\t11198\n8866\t169.6\t12265\n8572\t143.7\t11704\n9176\t160\t12419\n8645\t135.5\t13259\n8265\t141.7\t13945\n9558\t159.9\t13839\n7037\t145.6\t12387\n9101\t183.4\t12546\n8180\t198.1\t12038\n7072\t186.7\t11977\n3832\t171.9\t12336\n7253\t150.5\t11793\n8667\t163\t12877\n7658\t153.6\t11923\n8859\t152.8\t13306\n7291\t135.4\t13988\n7529\t148.3\t14002\n8715\t148.3\t14338\n8450\t133.5\t12867\n9085\t193.8\t12761\n8350\t208.4\t12449\n7080\t197\t12658\n'}

In [3]:
df_full = pd.read_csv("/content/cbe.dat", sep='\t')
df_full

     choc   beer   elec
0    1451   96.3   1497
1    2037   84.4   1463
2    2477   91.2   1648
3    2785   81.9   1595
4    2994   80.5   1777
..    ...    ...    ...
391  8715  148.3  14338
392  8450  133.5  12867
393  9085  193.8  12761
394  8350  208.4  12449
395  7080  197.0  12658

[396 rows x 3 columns]

In [4]:
df_full['Fecha'] = pd.period_range(start='1958-01', periods=len(df_full), freq='M')
df_full = df_full.set_index('Fecha')
df_full.head()

         choc  beer  elec
Fecha
1958-01  1451  96.3  1497
1958-02  2037  84.4  1463
1958-03  2477  91.2  1648
1958-04  2785  81.9  1595
1958-05  2994  80.5  1777

In [8]:
# OJO!!!!!!!!!!!!!!
# Modifica el nombre de la columna por aquella que deseas analizar:

# Remplaza 'NOMBRE' por:

# 'choc' : Producción de bienes a base de chocolate (toneladas)
# 'beer' : Producción de cerveza (millones de litros)
# 'elec' : Producción de electricidad (millones de kWh)

df = df_full['NOMBRE'].to_frame()
df

          beer
Fecha
1958-01   96.3
1958-02   84.4
1958-03   91.2
1958-04   81.9
1958-05   80.5
...        ...
1990-08  148.3
1990-09  133.5
1990-10  193.8
1990-11  208.4
1990-12  197.0

[396 rows x 1 columns]